CREATE TABLE receipts (
  id INT UNSIGNED AUTO_INCREMENT,
  uploaded TIME DEFAULT CURRENT_TIME(),
  merchant VARCHAR(255),
  amount DECIMAL(12,2),
  receipt_type INT UNSIGNED,

  PRIMARY KEY (id)
);
CREATE TABLE tags (
  uploaded TIME DEFAULT CURRENT_TIME(),
  tagID INT UNSIGNED AUTO_INCREMENT,
  receiptID INT,
  tagName VARCHAR(255),

  PRIMARY KEY (tagID)


);
